AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A example lambda showing usage of the function-error-alarms application.

Resources:
  # We could define a shared errors topic here, or export the topic from one app and
  # use it another using !GetAtt AppResource1.Outputs.ErrorsTopicArn
  # ErrorsTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicName: !Sub "${AWS::StackName}-alerts-alarm"

  TestLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Runtime: nodejs8.10
      Handler: index.handler
      InlineCode: >
        exports.handler = async (event, context) => {
          if (event.error) {
            throw new Error("I just errored!");
          }
          return {success: true}
        }

  FunctionErrorAlarms:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:623245082754:applications/function-errors-alarm
        SemanticVersion: 1.0.0
      Parameters:
        FunctionName0: !Ref TestLambda
        ErrorsTopicName: !Sub "${AWS::StackName}-alerts-alarm"

Outputs:
  TestLambda:
    Description: ARN of the test lambda
    Value: !Ref TestLambda
